"""add columns

Revision ID: 34fdbbb9543e
Revises: eed19f3fad6a
Create Date: 2024-09-01 16:10:55.432561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fdbbb9543e'
down_revision: Union[str, None] = 'eed19f3fad6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('foo', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('bar', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_user_foo'), 'user', ['foo', 'bar'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_foo'), 'user', type_='unique')
    op.drop_column('user', 'bar')
    op.drop_column('user', 'foo')
    # ### end Alembic commands ###
